baseurl = "http://shaydul.in/"
title = "Ruslan Shaydulin"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]

  description = '<!--[-->PhD candidate and coffee enthusiast<!--]--><br/><!--[-->Clemson University School of Computing<!--]-->'
  logoimage = "/images/rshaydu.png"
  copyright = "Ruslan Shaydulin"

[[params.social]]
  medium = "telegram"
  icon = "telegram"
  link = "http://t.me/rsln_s"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/rshaydu"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/rsln-s"

[languages]
[languages.en]
languageName = "English"
weight = 1
