baseurl = "http://shaydul.in/"
title = "Ruslan Shaydulin"
theme = "dimension"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[--> Science and coffee enthusiast <!--]-->'
  logoimage = "/images/rshaydu.png"
  copyright = "Ruslan Shaydulin"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/rshaydu"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/rsln-s"

[languages]
[languages.en]
languageName = "English"
weight = 1
